services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app-admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app-db
    volumes:
      - ./db:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
    depends_on:
      - postgres
    environment:
      DB: 'app-db'
      DB_HOST: 'postgres'
      DB_PORT: 5432
