import { Inter } from 'next/font/google';
import type { ReactNode } from 'react';
import './globals.css';

interface Props {
  children: ReactNode;
}

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(props: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>{props.children}</body>
    </html>
  );
}
