import StyledJsxRegistry from '@/components/StyledJsxRegistry';
import type { Metadata } from 'next';
import { JetBrains_Mono } from 'next/font/google';
import type { ReactNode } from 'react';
import './app.css';
import { Header } from './client-components/Header';
import './globals.css';

const font = JetBrains_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: ReactNode;
}

export default function RootLayout(props: Props) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        <StyledJsxRegistry>{props.children}</StyledJsxRegistry>
      </body>
    </html>
  );
}
